"""add unique index on nickname column of user table

Revision ID: 05de6b5bb335
Revises: 658618c88c3d
Create Date: 2020-08-16 11:58:39.819519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "05de6b5bb335"
down_revision = "658618c88c3d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_user_nickname"), "user", ["nickname"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_nickname"), "user", type_="unique")
    # ### end Alembic commands ###
