"""add column age to user table

Revision ID: 208b758f6d15
Revises: 9d05703acf8f
Create Date: 2020-08-16 10:24:09.506877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208b758f6d15'
down_revision = '9d05703acf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
