"""remove column name from account table

Revision ID: 658618c88c3d
Revises: 208b758f6d15
Create Date: 2020-08-16 11:02:56.804649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658618c88c3d'
down_revision = '208b758f6d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('name', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
