"""create account_balance table

Revision ID: 8df4551ea098
Revises: cf869fd4dec7
Create Date: 2020-08-16 12:33:03.156037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8df4551ea098"
down_revision = "cf869fd4dec7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_balance",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("balance", sa.Numeric(), nullable=False),
        sa.CheckConstraint(
            "balance > 0", name=op.f("ch_account_balance__balance_is_positive")
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["account.id"], name=op.f("fk_account_balance__id_account")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_balance")),
    )
    op.create_unique_constraint(
        op.f("uq_user__name_fullname"), "user", ["name", "fullname"]
    )
    op.create_unique_constraint(
        op.f("uq_user__nickname"), "user", ["nickname"]
    )
    op.drop_constraint("uq_user_name_fullname", "user", type_="unique")
    op.drop_constraint("uq_user_nickname", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_user_nickname", "user", ["nickname"])
    op.create_unique_constraint(
        "uq_user_name_fullname", "user", ["name", "fullname"]
    )
    op.drop_constraint(op.f("uq_user__nickname"), "user", type_="unique")
    op.drop_constraint(op.f("uq_user__name_fullname"), "user", type_="unique")
    op.drop_table("account_balance")
    # ### end Alembic commands ###
