"""add unique index for fullname and name of user table

Revision ID: cf869fd4dec7
Revises: 05de6b5bb335
Create Date: 2020-08-16 12:02:42.466950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf869fd4dec7"
down_revision = "05de6b5bb335"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_user_name_fullname"), "user", ["name", "fullname"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_name_fullname"), "user", type_="unique")
    # ### end Alembic commands ###
