"""create index for description column of account table

Revision ID: e15b5fac6f51
Revises: 8df4551ea098
Create Date: 2020-08-16 12:35:03.157973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e15b5fac6f51"
down_revision = "8df4551ea098"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_account__description"),
        "account",
        ["description"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account__description"), table_name="account")
    # ### end Alembic commands ###
